### ISSUE TITLE
change the screenshot gif

### ISSUE THREAD

**Issue by kuboosoft** [liszd/Popcorn-Time-Desktop#3]
For security is necessary change the screenshot gif for a simple logo of Popcorn Time. Change links io to git project, avoid community social... avoid link to binaries...

**Comment by whyliam** [comment]
Thank you!
Actually, https://github.com/popcorn-official/popcorn-desktop this is official github. 
So I do not know if I can change the popcorn links or community social without permission.

**Comment by kuboosoft** [comment]
@liszd  I think so, delete all community links; Popcorn Time is Open Source (gplv3) and we can change all. the links to 'io', facebook, google+, twitter, is tracked; isn't convenient for us :)

**Comment by whyliam** [comment]
@kuboosoft OK, thank you for you suggestion!
